name: mdmix-env
channels:
  - conda-forge
dependencies:
  - python=2.7
  - pip=19.3.1=py27_0
  - numpy=1.16
  - matplotlib
  - scipy
  - cftime
  - ambertools
  - netCDF4==1.5.3
  - mechanize
  - biopython==1.76
  - griddataformats
